DROP TABLE SALON_REPORT;

DROP TABLE SALON_APPOINTMENT;

DROP TABLE SALON_SERVICE;

DROP TABLE SALON_USER;

-- Create table for salon_professional
CREATE TABLE SALON_USER (
    USER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    IS_ACTIVE NUMBER(1) DEFAULT(0),
    STATUS NUMBER(1) DEFAULT(0), --flagged or warned.
    USER_TYPE VARCHAR2(15) DEFAULT ('client'), --client, professional, admin_user, admin_appoint, or admin_super.
    USERNAME VARCHAR2(30) NOT NULL UNIQUE,
    FULL_NAME VARCHAR2(100) DEFAULT NULL,
    EMAIL VARCHAR2(120) NOT NULL,
    USER_IMAGE VARCHAR2(30),
    PASSWORD_HASHED VARCHAR2(80) NOT NULL,
    PHONE_NUMBER VARCHAR2(80) NOT NULL,
    ADDRESS VARCHAR2(100) DEFAULT NULL,
    AGE NUMBER(3) NOT NULL,
    PAY_RATE DECIMAL(5, 2) DEFAULT(NULL),
    SPECIALTY VARCHAR2(15) DEFAULT(NULL),
    CONSTRAINT USER_PK PRIMARY KEY (USER_ID)
);

-- Create table for salon_service
CREATE TABLE SALON_SERVICE (
    SERVICE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    SERVICE_NAME VARCHAR2(35) NOT NULL,
    SERVICE_DURATION NUMBER(2) NOT NULL,
    SERVICE_PRICE NUMBER(5, 2) NOT NULL,
    SERVICE_MATERIALS VARCHAR2(35) NOT NULL,
    CONSTRAINT SERVICE_PK PRIMARY KEY (SERVICE_ID)
);

INSERT INTO SALON_SERVICE(
    SERVICE_NAME,
    SERVICE_DURATION,
    SERVICE_PRICE,
    SERVICE_MATERIALS
) VALUES(
    'Trimming',
    30,
    50,
    'Scissors, comb'
);

-- Create table for salon_appointment
CREATE TABLE SALON_APPOINTMENT (
    APPOINTMENT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    STATUS VARCHAR2(10) DEFAULT('pending'),
    APPROVED NUMBER(1) DEFAULT(1),
    DATE_APPOINTMENT DATE DEFAULT SYSDATE,
    CLIENT_ID NUMBER NOT NULL,
    PROFESSIONAL_ID NUMBER NOT NULL,
    SERVICE_ID NUMBER NOT NULL,
    SLOT VARCHAR2(10) DEFAULT ('9-10'),
    VENUE VARCHAR(20) DEFAULT ('cmn_room'),
    CONSTRAINT APPOINTMENT_PK PRIMARY KEY (APPOINTMENT_ID),
    CONSTRAINT APPOINTMENT_CLIENTFK FOREIGN KEY (CLIENT_ID) REFERENCES SALON_USER(USER_ID),
    CONSTRAINT APPOINTMENT_PROFESSIONALFK FOREIGN KEY (PROFESSIONAL_ID) REFERENCES SALON_USER(USER_ID),
    CONSTRAINT APPOINTMENT_SEVICEFK FOREIGN KEY (SERVICE_ID) REFERENCES SALON_SERVICE(SERVICE_ID)
);

-- Create table for salon_report
CREATE TABLE SALON_REPORT(
    REPORT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    USER_ID NUMBER NOT NULL,
    APPOINTMENT_ID NUMBER NOT NULL,
    DATE_REPORT DATE DEFAULT SYSDATE,
    TITLE VARCHAR2(50) NOT NULL,
    CLIENT_REPORT VARCHAR2(500),
    PROFESSIONAL_REPORT VARCHAR2(500),
    CONSTRAINT REPORT_PK PRIMARY KEY (REPORT_ID),
    CONSTRAINT REPORT_FK FOREIGN KEY (APPOINTMENT_ID) REFERENCES SALON_APPOINTMENT(APPOINTMENT_ID),
    CONSTRAINT REPORT_USER_FK FOREIGN KEY (USER_ID) REFERENCES SALON_USER(USER_ID)
);

INSERT INTO SALON_USER(
    USER_TYPE,
    USERNAME,
    FULL_NAME,
    EMAIL,
    USER_IMAGE,
    PASSWORD_HASHED,
    PHONE_NUMBER,
    ADDRESS,
    AGE
) VALUES(
    'admin_user',
    'user_manager1',
    'ADMIN_USER',
    'saloon.adminuser@gmail.com',
    'adminpfp.png',
    '$2b$12$pVPMylNY6cZniBAIj5DOfeHS4gRSSNRib8q0FJHH2WTfpgYA1mwoa',
    '5142222222',
    '5000 street 1 Canada',
    100
);

INSERT INTO SALON_USER(
    USER_TYPE,
    USERNAME,
    FULL_NAME,
    EMAIL,
    USER_IMAGE,
    PASSWORD_HASHED,
    PHONE_NUMBER,
    ADDRESS,
    AGE
) VALUES(
    'admin_super',
    'nasr',
    'ADMIN_SUPER',
    'saloon.adminuser@gmail.com',
    'adminpfp.png',
    '$2b$12$14P.P/NpWsWYuM37HM5oqOCUq1/Z.mpX7rZp6RsM5DDpQLYhwMTJW',
    '5142222222',
    '5000 street 1 Canada',
    100
);

INSERT INTO SALON_USER(
    USER_TYPE,
    USERNAME,
    FULL_NAME,
    EMAIL,
    USER_IMAGE,
    PASSWORD_HASHED,
    PHONE_NUMBER,
    ADDRESS,
    AGE
) VALUES(
    'admin_appoint',
    'appoint_manager1',
    'ADMIN_APPOINT',
    'saloon.admin@gmail.com',
    'adminpfp.png',
    '$2b$12$dqjq50fQ6cbbMAduE4FUfOJGVRnRas.aaMG6X4pujumPpm7WafnVW',
    '5142222222',
    '5000 street 1 Canada',
    100
);

INSERT INTO SALON_USER(
    USER_TYPE,
    USERNAME,
    FULL_NAME,
    EMAIL,
    USER_IMAGE,
    PASSWORD_HASHED,
    PHONE_NUMBER,
    ADDRESS,
    AGE,
    SPECIALTY,
    PAY_RATE
) VALUES(
    'professional',
    'Michelle_BelHair',
    'Michelle Bellaire',
    'Michelle.hair@outlook.com',
    'michelle.png',
    '$2b$12$lgb37fRBrPOg17wTlCD4yuKldS4xedBS2V.iXgiQNxu.gk1mIciMG',
    '7010 street 1',
    '5142222222',
    51,
    'curly hair',
    100
);

INSERT INTO SALON_APPOINTMENT (
    CLIENT_ID,
    PROFESSIONAL_ID,
    SERVICE_ID,
    SLOT,
    VENUE,
    DATE_APPOINTMENT
) VALUES (
    (SELECT USER_ID FROM SALON_USER WHERE USERNAME = 'nasr'),
    (SELECT USER_ID FROM SALON_USER WHERE USERNAME = 'Michelle_BelHair'),
    (SELECT SERVICE_ID FROM SALON_SERVICE WHERE SERVICE_NAME = 'Trimming'),
    '10-11',
    '1',
    SYSDATE
);

INSERT INTO SALON_APPOINTMENT (
    CLIENT_ID,
    PROFESSIONAL_ID,
    SERVICE_ID,
    SLOT,
    VENUE,
    DATE_APPOINTMENT
) VALUES (
    (SELECT USER_ID FROM SALON_USER WHERE USERNAME = 'nasr'),
    (SELECT USER_ID FROM SALON_USER WHERE USERNAME = 'Michelle_BelHair'),
    (SELECT SERVICE_ID FROM SALON_SERVICE WHERE SERVICE_NAME = 'Trimming'),
    '10-11',
    '1',
    SYSDATE
);

---Insert Valuesfor user member
INSERT INTO SALON_USER(
    USERNAME,
    FULL_NAME,
    EMAIL,
    USER_IMAGE,
    PASSWORD_HASHED,
    PHONE_NUMBER,
    ADDRESS,
    AGE
) VALUES(
    'iana_life',
    'Iana Feniuc',
    'ianafeniuc@gmail.com',
    'user.png',
    'sjkdhuvb',
    '514-567-1567',
    '2135 Boul Russeau',
    19
);

SELECT
    USER_ID,
    IS_ACTIVE,
    USER_TYPE,
    STATUS,
    USERNAME,
    FULL_NAME,
    EMAIL,
    USER_IMAGE,
    PASSWORD_HASHED,
    PHONE_NUMBER,
    ADDRESS,
    AGE,
    SPECIALTY,
    PAY_RATE
FROM
    SALON_USER
WHERE
    USERNAME = 'nasr';

SELECT * FROM salon_report WHERE appointment_id = 8;

UPDATE salon_user
                        SET user_type = 'client',
                            username = 'RidaClient',
                            full_name = 'Rida EDITED',
                            password_hashed = '$2b$12$y7YQtBlvQ7EtKsFOSpYdaO8yKTU6os66jJfr/8skkXO0DJvM66zw.',
                            email = 'rida@gmail.com',
                            phone_number = '5142222222',
                            address = '5000 Montreal',
                            age = 19,
                            specialty = 'janitor',
                            pay_rate = 10,
                            user_image = 'default.png'
                        WHERE user_id = 21;